stages:
  - deploy

deploy_production:
  stage: deploy
  image: node:20-alpine
  tags:
    - azure-runner
  before_script:
    - apk add --no-cache openssh-client rsync
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    # Trik bypass SSH Keyscan: Matikan fitur Strict Host Key Checking!
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - tr -d '\r' < "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-add ~/.ssh/id_rsa
  script:
    - echo "1. Menginstal dependensi Node.js & Build Assets Vite..."
    - npm install
    - npm run build
    
    - echo "2. Transfer code ke Azure VM via Rsync..."
    - rsync -avz --exclude='.git' --exclude='node_modules' --exclude='/storage' --exclude='.env' ./ $SERVER_USER@$SERVER_HOST:/home/muhaqieladhirajendra/htdocs/muhaqieladhirajendra.dev/
    
    - echo "3. Menjalankan Command Laravel di dalam Azure VM via SSH..."
    - ssh $SERVER_USER@$SERVER_HOST "
        cd /home/muhaqieladhirajendra/htdocs/muhaqieladhirajendra.dev &&
        
        echo 'Menginstal dependensi PHP...' &&
        composer install --optimize-autoloader --no-dev &&
        
        echo 'Konfigurasi .env...' &&
        if [ ! -f .env ]; then cp .env.example .env; php artisan key:generate; fi &&
        
        echo 'Migrasi Database...' &&
        php artisan migrate --force &&
        
        echo 'Membuat Storage Link...' &&
        php artisan storage:link || true &&
        
        echo 'Optimasi Cache Laravel...' &&
        php artisan optimize:clear &&
        php artisan optimize &&
        
        echo 'Mengatur permission folder...' &&
        chmod -R 777 storage bootstrap/cache || sudo chmod -R 777 storage bootstrap/cache
      "
    - echo "Deploy Sukses ke Path yang Benar!"
  only:
    - main